name: 'Write2Inventory'
description: 'Write all NuGet, NPM and Submodule information into a Repository'
author: 'ARall'
branding:
  icon: 'check'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub token'
    required: false
    default: ./
  branch-name:
    description: 'Name of the branch to get information for'
    required: false
    default: ./
  output-path:
    description: 'Path to output JSON file'
    required: false
    default: ./report.json
  updateStrategy:
    description: 'The update strategy to use: "MAJOR", "MINOR", or "PATCH". Defaults to "MINOR".'
    required: false
    default: 'MINOR'
  sources:
    description: 'List of sources for nuget seperated by new line'
    required: false
    default: 'https://api.nuget.org'
  npmSources:
    description: 'List of sources for npm seperated by new line'
    required: false
    default: '"https://registry.npmjs.org/@actions'
  submoduleURLs:
    description: 'List of sources for npm seperated by new line'
    required: false
    default: ''



runs:
  using: 'node16'
  main: 'dist/index.js'