' @startjson
' {
'   "repository": {
'     "name": "string",
'     "currentReleaseTag": "string",
'     "license": "string",
'     "sha": "string"
'   },
'   "npmPackages": [
'     {
'       "name": "string",
'       "version": "string",
'       "repoName": "string",
'       "owner": "string"
'     }
'   ],
'   "nugetPackages": [
   
'     {
'       "project": "string",
'       "source": "string",
'       "packageName": "string",
'       "currentVersion": "string",
'       "resolvedVersion": "sring",
'       "latestVersion": "string"
'     }
'   ],
'   "submodules": [

'     {
'       "sha": "string",
'       "submoduleName": "string",
'       "referenceBranch": "string"
'     }
'   ],
'   "updateStrategy": "enum"
' }
' @endjson

@startjson
{
  "type": "object",
  "properties": {
    "repository": {
      "type": "object",
      "properties": {
        "orgName": {
          "type": "string"
        },
        "repoName": {
          "type": "string"
        },
        "currentReleaseTag": {
          "type": "string"
        },
        "license": {
          "type": "string"
        },
        "sha": {
          "type": "string"
        }
      },
      "required": [
        "orgName",
        "repoName",
        "currentReleaseTag",
        "license",
        "sha"
      ]
    },
    "InternnpmPackages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            },
            "latestVersion": {
              "type": "string"
            },
            "resolved": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "currentVersion",
            "latestVersion",
            "resolved"
          ]
        }
      ]
    },
    "ExternnpmPackages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            },
            "latestVersion": {
              "type": "string"
            },
            "resolved": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "currentVersion",
            "latestVersion",
            "resolved"
          ]
        }
      ]
    },
    "OutdatedNugetPackages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "project": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "packageName": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            },
            "resolvedVersion": {
              "type": "string"
            },
            "latestVersion": {
              "type": "string"
            }
          },
          "required": [
            "project",
            "source",
            "packageName",
            "currentVersion",
            "resolvedVersion",
            "latestVersion"
          ]
        }
      ]
    },
    "AllNugetPackages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "project": {
              "type": "string"
            },
            "source": {
              "type": "string"
            },
            "packageName": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            }
          },
          "required": [
            "project",
            "source",
            "packageName",
            "currentVersion"
          ]
        }
      ]
    },
    "submodules": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "sha": {
              "type": "string"
            },
            "submoduleName": {
              "type": "string"
            },
            "referenceBranch": {
              "type": "string"
            }
          },
          "required": [
            "sha",
            "submoduleName",
            "referenceBranch"
          ]
        }
      ]
    },
    "updateStrategy": {
      "type": "string"
    },
    "NugetDependencies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "currentVersion"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "currentVersion"
          ]
        }
      ]
    },
    "NpmDependencies": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "currentVersion": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "currentVersion"
          ]
        }
      ]
    }
  },
  "required": [
    "repository",
    "InternnpmPackages",
    "ExternnpmPackages",
    "OutdatedNugetPackages",
    "AllNugetPackages",
    "submodules",
    "updateStrategy",
    "NugetDependencies",
    "NpmDependencies"
  ]
}
@endjson